name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            persist-credentials: false

      - name: Install and Build
        run: yarn install && yarn run build --base=/My_blog/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          personal_token: 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
          REPOSITORY_NAME: somenzz/somenzz.github.io
          BRANCH: master
          FOLDER: docs/.vuepress/dist
