name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
   name: deploy to staging
   runs-on: ubuntu-18.04
   strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]
   steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.17.1
      uses: actions/setup-node@v1
      with:
        node-version: 16.17.1

    - name: Install and Build
      run: yarn install && yarn run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          personal_token: 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
          REPOSITORY_NAME: somenzz/somenzz.github.io
